# ==============================================================================
#                                INTEGRATIONS
# ==============================================================================
# KernelSU & SUSFS versions
# https://github.com/tiann/KernelSU/commits/main/
# https://gitlab.com/simonpunk/susfs4ksu/-/tree/gki-android14-6.1
# To update these components, specify the latest commit hashes from the repositories above
KSU_COMMIT="5018d57a49da27ae9d717c362ab0fd1526c54a15"
SUSFS_KSU_COMMIT="e287d59066380bf6de4396532d4a42edf4408701"

# Base kernel source patches
# Applied before compilation but after KSU and SUSFS integration
KERNELSOURCE_PATCHES=(
    "fix_namespace.c.patch"
)

# ==============================================================================
#                                AVB METADATA
# ==============================================================================
# Filled based on the AVB metadata of the original boot.img.
# Changing these fields is not strictly necessary, but can be done if required.
# To extract the data, use avbtool.py:
#   python3 ./avbtool.py info_image --image [original_boot.img]
#   Link to avbtool.py: https://android.googlesource.com/platform/external/avb/+/refs/heads/main-kernel/avbtool.py

STABLE_rollback_index=1785888000
STABLE_salt=6caae4112961def27eeacd6573fb2417a926db7e6619a8aec1f8c3cf70a70ade
STABLE_os_version=17
STABLE_fingerprint=google/shiba/shiba:17/CP2A.260805.005/15828068:user/release-keys
STABLE_security_patch=2026-08-05

BETA_rollback_index=1783209600
BETA_salt=4c94eb5419604ca26805bf8d0f2f0994f57b3dc506b72ed4f459b06319d36c37
BETA_os_version=17
BETA_fingerprint=google/shiba_beta/shiba:DEV/CP41.260717.006/15938186:user/release-keys
BETA_security_patch=2026-07-05

# ==============================================================================
#                                FIRMWARE BRANCHES
# ==============================================================================
# Determines the GKI kernel source branch cloned from: https://android.googlesource.com/kernel/common/+refs
# To choose the correct branch, check the "Makefile" in the root of the kernel repository.
# The version numbers are specified in the Makefile header (e.g., VERSION = 6, PATCHLEVEL = 1, SUBLEVEL = 157).
# This version must match the kernel version of your installed firmware.

STABLE_BRANCH="android14-6.1-2025-12"
BETA_BRANCH="android14-6.1-2026-03"

# ==============================================================================
#                        BUILD TOOLS & PIXEL DRIVERS
# ==============================================================================
# Contains drivers, build tools, etc.
# Cloned from: https://gitlab.com/grapheneos/kernel_pixel
# DO NOT CHANGE unless you know what you are doing
PIXEL_TAG="2026062800"

# ==============================================================================
#             EXPERIMENTAL INTEGRATIONS (REQUIRES MANUAL FIXES)
# ==============================================================================
# KernelSU-Next & SukiSU integration

KSU_NEXT_COMMIT="HEAD"
SUSFS_COMMIT="4a1e8311ae24bffb82c97b15945a7d94bf04cf90"
