name: Build Kernel

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      firmware:
        type: choice
        description: "Firmware type"
        default: stable
        options:
          - stable
          - beta
      ksu_type:
        type: choice
        description: "KernelSU type"
        default: ksu
        options:
          - ksu
          - ksun
          - sukisu

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - id: set
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo 'matrix={"firmware":["${{ inputs.firmware }}"],"ksu_type":["${{ inputs.ksu_type }}"]}' >> $GITHUB_OUTPUT
          else
            echo 'matrix={"firmware":["stable","beta"],"ksu_type":["ksu"]}' >> $GITHUB_OUTPUT
          fi

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: true
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full zip git curl wget

      - name: First Install
        run: ./first_install.sh

      - name: Build Kernel
        run: ./build_ksu.sh --${{ matrix.firmware }} --${{ matrix.ksu_type }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: boot_${{ matrix.firmware }}_${{ matrix.ksu_type }}
          path: output/*
          retention-days: 1
          archive: true
